language: cpp
sudo: enabled
os: linux

addons:
  apt:
    packages:
     - gnupg grep sed

env:
  - FILE=dfsg/main/bidiv.scm
  - FILE=dfsg/main/brendan_gregg.scm
  - FILE=dfsg/main/confclerk.scm
  - FILE=dfsg/main/cpuid2cpuflags.scm
  - FILE=dfsg/main/ecrire.scm
  - FILE=dfsg/main/equate.scm
  - FILE=dfsg/main/evisum.scm
  - FILE=dfsg/main/html2text.scm
  - FILE=dfsg/main/mcron.scm
  - FILE=dfsg/main/micropython.scm
  - FILE=dfsg/main/mpv.scm
  - FILE=dfsg/main/mupdf.scm
  - FILE=dfsg/main/nyancat.scm
  - FILE=dfsg/main/ponyos.scm
  - FILE=dfsg/main/pinentry-efl.scm
  - FILE=dfsg/main/rtv.scm
  - FILE=dfsg/main/viiper.scm
  - FILE=dfsg/main/wgetpaste.scm
  - FILE=dfsg/main/xorriso.scm
  - FILE=dfsg/contrib/dropbox.scm

install:
    - wget "https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh?h=v0.16.0" -O guix-install.sh
    - until gpg --recv-keys 3CE464558A84FDC69DB40CFB090B11993D9AEBB5; do echo "trying again..."; done
    - echo -e 'y\ny' | sudo bash guix-install.sh
    - sudo mkdir -p /var/guix/profiles/per-user/travis
    - sudo chown travis:travis /var/guix/profiles/per-user/travis
    - guix pull --fallback --substitute-urls="https://ci.guix.info https://mirror.hydra.gnu.org"

script:
    - GUIX_PACKAGE_PATH=. guix build --no-grafts --fallback --substitute-urls="https://ci.guix.info https://mirror.hydra.gnu.org" $(grep define-public $FILE | cut -f2 -d' ')

notifications:
    email:
        on_success: never
        on_failure: always

git:
    depth: 10
