os: linux
sudo: enabled
language: minimal

addons:
  apt:
    packages:
      - gnupg wget grep sed

env:
  #  - FILE: dfsg/main/arcticfox.scm  # log length too long
  - FILE: dfsg/main/brendan_gregg.scm
  - FILE: dfsg/main/cpuid2cpuflags.scm
  - FILE: dfsg/main/ecrire.scm
  - FILE: dfsg/main/enlightenment.scm
  - FILE: dfsg/main/equate.scm
  - FILE: dfsg/main/eterm.scm
  - FILE: dfsg/main/etui.scm
  - FILE: dfsg/main/express.scm
  - FILE: dfsg/main/girst.scm
  - FILE: dfsg/main/moreutils.scm
  - FILE: dfsg/main/parcimonie.scm
  - FILE: dfsg/main/pifs.scm
  - FILE: dfsg/main/pinentry-efl.scm
  - FILE: dfsg/main/pipx.scm
  - FILE: dfsg/main/psd.scm
  - FILE: dfsg/main/rdrview.scm
  - FILE: dfsg/main/sigil.scm
  - FILE: dfsg/main/vim.scm
    # - FILE: dfsg/contrib/keybase.scm  # log length too long
  - FILE: dfsg/contrib/linode.scm
  - FILE: dfsg/contrib/onedrive.scm
  - FILE: dfsg/non-free/parallel.scm

install: |
  travis_retry wget http://guix.gnu.org/install.sh -O guix-install.sh
  travis_retry wget "https://savannah.gnu.org/project/memberlist-gpgkeys.php?group=guix&download=1" -qO - | gpg --import -
  echo -e 'y\ny' | sudo bash guix-install.sh
  sudo mkdir -p /var/guix/profiles/per-user/travis
  sudo chown travis:travis /var/guix/profiles/per-user/travis
  travis_retry guix pull --fallback

script: |
  export PATH="~/.config/guix/current/bin${PATH:+:}$PATH"
  GUIX_PACKAGE_PATH=. guix build --no-grafts --fallback $(grep define-public $FILE | cut -f2 -d' ')

notifications:
  email:
    on_success: never
    on_failure: always

git:
  depth: 1
