os: linux
sudo: enabled
language: minimal

addons:
  apt:
    packages:
     - gnupg wget grep sed

env:
  - FILE=dfsg/main/bidiv.scm
  - FILE=dfsg/main/brendan_gregg.scm
  - FILE=dfsg/main/confclerk.scm
  - FILE=dfsg/main/cpuid2cpuflags.scm
  - FILE=dfsg/main/ecrire.scm
  - FILE=dfsg/main/equate.scm
  - FILE=dfsg/main/evisum.scm
  - FILE=dfsg/main/html2text.scm
  - FILE=dfsg/main/mcron.scm
  - FILE=dfsg/main/minesviiper.scm
  - FILE=dfsg/main/mpv.scm
  - FILE=dfsg/main/mupdf.scm
  - FILE=dfsg/main/nyancat.scm
  - FILE=dfsg/main/parcimonie.scm
  - FILE=dfsg/main/ponyos.scm
  - FILE=dfsg/main/pinentry-efl.scm
  - FILE=dfsg/main/solvitaire.scm
  - FILE=dfsg/main/viper.scm
  - FILE=dfsg/main/xorriso.scm
  - FILE=dfsg/contrib/dropbox.scm

install:
    - travis_retry wget "https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh?h=v1.0.1" -O guix-install.sh
    - travis_retry gpg --recv-keys 3CE464558A84FDC69DB40CFB090B11993D9AEBB5
    - echo -e 'y\ny' | sudo bash guix-install.sh
    - sudo mkdir -p /var/guix/profiles/per-user/travis
    - sudo chown travis:travis /var/guix/profiles/per-user/travis
    - guix pull --fallback

script:
    - export PATH="~/.config/guix/current/bin${PATH:+:}$PATH"
    - GUIX_PACKAGE_PATH=. guix build --no-grafts --fallback $(grep define-public $FILE | cut -f2 -d' ')

notifications:
    email:
        on_success: never
        on_failure: always

git:
    depth: 1
